# -*- coding=utf-8 -*-
dict={
            'PI': {'type': 'CONST_ID', 'value': 3.1415926},
            'E': {'type': 'CONST_ID', 'value': 2.71828},
            'T': {'type': 'T', 'value': 0.0},
            'SIN': {'type': 'FUNC', 'value': 0.0},
            'COS': {'type': 'FUNC', 'value': 0.0},
            'TAN': {'type': 'FUNC', 'value': 0.0},
            'LN': {'type': 'FUNC', 'value': 0.0},
            'EXP': {'type': 'FUNC', 'value': 0.0},
            'SQRT': {'type': 'FUNC', 'value': 0.0},
            'ORIGIN': {'type': 'ORIGIN', 'value': 0.0},
            'SCALE': {'type': 'SCALE', 'value': 0.0},
            'ROT': {'type': 'ROT', 'value': 0.0},
            'IS': {'type': 'IS', 'value': 0.0},
            'FOR': {'type': 'FOR', 'value': 0.0},
            'FROM': {'type': 'FROM', 'value': 0.0},
            'TO': {'type': 'TO', 'value': 0.0},
            'STEP': {'type': 'STEP', 'value': 0.0},
            'DRAW': {'type': 'DRAW', 'value': 0.0},
            '+': {'type': 'PLUS', 'value': 0.0},
            '-': {'type': 'MINUS', 'value': 0.0},
            '*': {'type': 'MUL', 'value': 0.0},
            '/': {'type': 'DIV', 'value': 0.0},
            '**': {'type': 'POWER', 'value': 0.0},
            ';': {'type': 'SEMICO', 'value': 0.0},
            '(': {'type': 'L_BRACKET', 'value': 0.0},
            ')': {'type': 'R_BRACKET', 'value': 0.0},
            ',': {'type': 'COMMA', 'value': 0.0},
        }

